name: taboo-brittleness
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - pytorch
  - numpy
  - pandas
  - matplotlib
  - pyyaml
  - scipy
  - pip:
      - transformers>=4.41
      - transformer_lens
      - nnsight
      - sae-lens
