models:
  - bcywinski/gemma-2-9b-it-taboo-ship
layer_of_interest: 32
budgets:
  sae_latents: [1, 2, 4, 8, 16, 32]
  lowrank: [1, 2, 4, 8]
seeds: [31, 42, 404]
paths:
  data_dir: data
  results_dir: results
  sae_dir: third_party/saes/gemma2-9b-it_l32_16k
